[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["echo 'Skipping npm ci - installing only required dependencies'"]

[phases.build]
cmds = ["npm install socket.io@^4.8.1 @supabase/supabase-js@^2.58.0 dotenv@^17.2.3 --production"]

[start]
cmd = "node src/lib/socket-server.js"
